# Generated by Django 5.0.1 on 2026-03-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_address_alter_hooattendee_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
